name: Trivy
on:
  workflow_dispatch:
    inputs:
        image:
          description: Image identifier
          required: true
          default: golang
        tag:
          description: Image tag
          required: false
          default: 1.12
jobs:
  build:
    name: Vulnerability scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Call my composite action
        uses: ./.github/actions/composite
        with:
          image: ${{ github.event.inputs.image }}
          tag: ${{ github.event.inputs.tag }}
