name: Trivy
on:
  workflow_dispatch:
    inputs:
        image:
          description: Image identifier
          required: true
          default: golang
        tag:
          description: Image tag
          required: false
          default: 1.12
jobs:
  build:
    name: Vulnerability scanning
    runs-on: ubuntu-18.04
    steps:
      - name: Run Trivy vulnerability scanner
        uses: tanguyseg/trivy-action@master
        with:
          image-ref: ${{ github.event.inputs.image }}:${{ github.event.inputs.tag }}
          format: table
          exit-code: 0
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
